py_binary(
    name = "client",
    srcs = ["client.py"],
    default_python_version = "PY3",
    srcs_version = "PY3",
    deps = [
        "//geoproxy:geoproxy_py",
    ],
)

py_binary(
    name = "server",
    srcs = ["server.py"],
    default_python_version = "PY3",
    srcs_version = "PY3",
    deps = [
        "//geoproxy:geoproxy_py",
    ],
)